services:
  - type: web
    name: syncstage
    runtime: docker
    dockerfilePath: ./Dockerfile.allinone
    dockerContext: .
    plan: free
    healthCheckPath: /api/health

    envVars:
      - key: DATABASE_URL
        sync: false

      - key: CYCLE_SECONDS
        value: "18000"

      - key: ALLOWED_ORIGINS
        value: "*"